library(plotly)
library(ggplot2)
nba <- read.csv("combined_data.csv")
rnames <- nba[,1]
mat_nba <- data.matrix(nba[,2:ncol(nba)])
rownames(mat_nba) <- rnames
df <- data.frame(mat_nba)
plot(x= df$X, y=df$Y)
abline(h = 1)
abline(h = -1)
abline(v = 0.5)
abline(v = -0.5)
quadrant_1 <- data.frame((df$X > 0.5) & (df$Y > 1))
write.csv(quadrant_1, "C:/Users/manis/Desktop/manisha_aswal/transcriptomics_proteomics_work/quadrant_1.csv" )
quadrant_2 <- data.frame((df$X < -0.5) & (df$Y > 1))
write.csv(quadrant_2, "C:/Users/manis/Desktop/manisha_aswal/transcriptomics_proteomics_work/quadrant_2.csv" )
quadrant_3 <- data.frame((df$X < -0.5) & (df$Y < -1))
write.csv(quadrant_3, "C:/Users/manis/Desktop/manisha_aswal/transcriptomics_proteomics_work/quadrant_3.csv" )
quadrant_4 <- data.frame((df$X > 0.5) & (df$Y < -1))
write.csv(quadrant_4, "C:/Users/manis/Desktop/manisha_aswal/transcriptomics_proteomics_work/quadrant_4.csv" )
quadrant_5 <- data.frame((df$X > 0.5) & (df$Y > -1) & (df$Y < 1))
write.csv(quadrant_5, "C:/Users/manis/Desktop/manisha_aswal/transcriptomics_proteomics_work/quadrant_5.csv" )
quadrant_6 <- data.frame((df$X > -0.5) & (df$X < 0.5) & (df$Y > 1))
write.csv(quadrant_6, "C:/Users/manis/Desktop/manisha_aswal/transcriptomics_proteomics_work/quadrant_6.csv" )
quadrant_7 <- data.frame((df$X < -0.5) & (df$Y > -1) & (df$Y < 1))
write.csv(quadrant_7, "C:/Users/manis/Desktop/manisha_aswal/transcriptomics_proteomics_work/quadrant_7.csv" )
quadrant_8 <- data.frame((df$X > -0.5) & (df$X < 0.5) & (df$Y < -1))
write.csv(quadrant_8, "C:/Users/manis/Desktop/manisha_aswal/transcriptomics_proteomics_work/quadrant_8.csv" )
quadrant_9 <- data.frame((df$X > -0.5) & (df$X < 0.5) & (df$Y < 1) & (df$Y > -1))
write.csv(quadrant_9, "C:/Users/manis/Desktop/manisha_aswal/transcriptomics_proteomics_work/quadrant_9.csv" )
